### ISSUE TITLE
Gurobi Solver - Error in dyn.load(file, DLLpath = DLLpath, ...)

### ISSUE THREAD

**Issue by michelesantacatterina** [rstudio/markdown#91]
Hi everyone,

I am trying to embed some R code to solve an optimization problem with Gurobi. This is a simple example:

---
title: "Test Gurobi"
author: "Michele Santacatterina"
date: "6/21/2018"
output: pdf_document
---

## R Markdown

This is a test

```{r}
library(gurobi)
```

However, I get the following error:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/gurobi/libs/gurobi.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/gurobi/libs/gurobi.so, 6): Library not loaded: libgurobi70.so
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/gurobi/libs/gurobi.so
  Reason: image not found
Quitting from lines 19-20 (Untitled.Rmd) 
Error: package or namespace load failed for 'gurobi'
Execution halted

Any idea on how to solve this?

Thank you,

Michele

**Comment by yihui** [comment]
I don't think this is an rmarkdown issue. Please try to [StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) or [RStudio Community](https://community.rstudio.com) instead. Thanks!

BTW, please read the issue template carefully the next time when you file an issue, to make sure your issue is correct formatted (in particular, please check out [the four-backtick rule](https://yihui.name/en/2017/05/four-backticks-github/)).

**Comment by yihui** [comment]
P.S. This is the **markdown** repo, not **rmarkdown**.
